# Created by: Mathieu Simon <freebsd@simweb.ch>
# $FreeBSD$

PORTNAME=	Parse-EDID
PORTVERSION=	1.0.6
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	freebsd@simweb.ch
COMMENT=	Perl extension for parsing extended display identification data (EDID)

LICENSE=	GPLv3

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
