#!/bin/sh

# $FreeBSD$
#
# PROVIDE: lldpd
# REQUIRE: LOGIN
# KEYWORD: shutdown
# 
# Add these lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
# 
# lldpd_enable (bool):	Set to NO by default.
#			Set it to YES to enable lldpd.
# lldpd_config (path):	Set to %%PREFIX%%/etc/lldpd/lldpd.conf
#			by default.

. /etc/rc.subr

name=lldpd
rcvar=lldpd_enable

load_rc_config $name

: ${lldpd_enable:="NO"}
: ${lldpd_config="%%PREFIX%%/etc/lldpd.conf}

command=%%PREFIX%%/sbin/${name}



# $OpenBSD: lldpd.rc,v 1.2 2013/07/15 21:35:46 sthen Exp $

daemon="${TRUEPREFIX}/sbin/lldpd"
rc_reload=NO

. /etc/rc.d/rc.subr

pexp="lldpd: monitor"

rc_pre() {
	install -d -o _lldpd /var/run/lldpd
}

